### ISSUE TITLE
Unclear mention

### ISSUE THREAD

**Issue by algebraic-dev** [matklad/resilient-ll-parsing#1]
I would like to know wdym by Layer Typed accessor.

> One possible design here is to make the underlying tree a dynamically-typed data structure (like JSON), and layer typed accessors on top (not covered in this article).

**Comment by matklad** [comment]
Yeah… I am yet to write this some day, but this topic is covered in this video:

* https://m.youtube.com/watch?v=Qe3sidZQt0c&list=PLhb66M_x9UmrqXhQuIpWC5VgTdrGxMx3y&index=9&pp=iAQB


(https://m.youtube.com/watch?v=n5LDjWIAByM&list=PLhb66M_x9UmrqXhQuIpWC5VgTdrGxMx3y&index=8&pp=iAQB is the previous episode, which sets the contex)
